"""Reproducible multi-model Realistic NIAH counting experiments."""

from .spec import (
    FORMAL_PROMPT_MODES,
    MATCHED_CONTROL_MODEL_LABELS,
    MATCHED_NONTHINKING_CONTROLS,
    MODEL_REVISIONS,
    MODEL_SPECS,
    NEEDLE_COUNTS,
    NONTHINKING_PROMPT_MODES,
    PASSAGE_LENGTHS,
    PRIMARY_MODEL_LABELS,
    QUERY_LAYOUT,
    SEEDS,
    SMOKE_NEEDLE_COUNTS,
    SMOKE_PASSAGE_LENGTHS,
    ModelSpec,
)

__all__ = [
    "MODEL_SPECS",
    "FORMAL_PROMPT_MODES",
    "NONTHINKING_PROMPT_MODES",
    "PRIMARY_MODEL_LABELS",
    "MATCHED_CONTROL_MODEL_LABELS",
    "MATCHED_NONTHINKING_CONTROLS",
    "MODEL_REVISIONS",
    "NEEDLE_COUNTS",
    "PASSAGE_LENGTHS",
    "QUERY_LAYOUT",
    "SEEDS",
    "SMOKE_NEEDLE_COUNTS",
    "SMOKE_PASSAGE_LENGTHS",
    "ModelSpec",
]
