"""Single-example Dynamic NIAH analysis helpers."""

from .ablation_analysis import (
    DEFAULT_ABLATION_CONFIG_PATH,
    AblationConfig,
    build_irrelevant_token_pool,
    load_ablation_config,
    run_single_example_ablation,
    select_critical_tokens,
    summarize_ablation_results_all,
)

from .ablation_representation_analysis import (
    DEFAULT_REPRESENTATION_ABLATION_CONFIG_PATH,
    RepresentationAblationConfig,
    active_ablation_layers,
    load_representation_ablation_config,
    profile_hidden_state_distribution,
    run_single_example_representation_ablation,
    select_representation_critical_tokens,
)

from .ablation_representation_analysis_restore import (
    DEFAULT_REPRESENTATION_RESTORE_CONFIG_PATH,
    RepresentationRestoreConfig,
    load_representation_restore_config,
    resolve_restore_dataset_path,
    run_single_example_representation_restore,
    select_representation_restore_critical_tokens,
)
from .single_example_analysis import (
    DEFAULT_DATASET_PATH,
    SingleExamplePaths,
    TokenizedPrompt,
    build_single_example_config,
    cleanup_large_tensor_artifacts,
    compute_single_example_hidden_states,
    create_single_example_run,
    load_jsonl_example,
    load_model_and_tokenizer,
    locate_uncontrolled_needle_segments,
    prepare_single_example_dataset,
    render_and_tokenize_messages,
    run_single_example_qk_outlier_analysis,
    save_input_metadata,
    zip_single_example_results,
)

__all__ = [
    "DEFAULT_REPRESENTATION_RESTORE_CONFIG_PATH",
    "RepresentationRestoreConfig",
    "load_representation_restore_config",
    "resolve_restore_dataset_path",
    "run_single_example_representation_restore",
    "select_representation_restore_critical_tokens",
    "DEFAULT_REPRESENTATION_ABLATION_CONFIG_PATH",
    "RepresentationAblationConfig",
    "active_ablation_layers",
    "load_representation_ablation_config",
    "profile_hidden_state_distribution",
    "run_single_example_representation_ablation",
    "select_representation_critical_tokens",
    "DEFAULT_ABLATION_CONFIG_PATH",
    "DEFAULT_DATASET_PATH",
    "AblationConfig",
    "SingleExamplePaths",
    "TokenizedPrompt",
    "build_irrelevant_token_pool",
    "build_single_example_config",
    "cleanup_large_tensor_artifacts",
    "compute_single_example_hidden_states",
    "create_single_example_run",
    "load_ablation_config",
    "load_jsonl_example",
    "load_model_and_tokenizer",
    "locate_uncontrolled_needle_segments",
    "prepare_single_example_dataset",
    "render_and_tokenize_messages",
    "run_single_example_ablation",
    "run_single_example_qk_outlier_analysis",
    "save_input_metadata",
    "select_critical_tokens",
    "summarize_ablation_results_all",
    "zip_single_example_results",
]
