from __future__ import annotations

import hashlib
import json
from collections import Counter
from dataclasses import asdict
from pathlib import Path
from typing import Any, Iterable, Mapping

from .parsing import parse_trace_record
from realistic_niah_v4.spec import resolve_model_spec

from .spec import GENERATION_SCHEMA_VERSION, PROTOCOL_VERSION, V6Config


EXPECTED_SOURCE_STIMULI_SHA256 = (
    "da4dd86142eb8a07f9a7e53497efd3375184c8e68367d4db994370fcb331f090"
)


def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with Path(path).open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(f"Invalid JSONL line {line_number}: {error}") from error
            if not isinstance(value, dict):
                raise ValueError(f"JSONL line {line_number} is not an object")
            rows.append(value)
    return rows


def write_jsonl(path: str | Path, rows: Iterable[Mapping[str, Any]]) -> int:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(target.name + ".tmp")
    count = 0
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(json.dumps(dict(row), ensure_ascii=False, sort_keys=True) + "\n")
            count += 1
    temporary.replace(target)
    return count


def validate_generation_contracts(
    rows: Iterable[Mapping[str, Any]],
    config: V6Config,
    *,
    model_label: str | None = None,
    config_sha256: str | None = None,
) -> dict[str, Any]:
    """Fail closed if a mechanism input was not generated by this V6 contract."""

    config.validate()
    materialized = list(rows)
    errors: list[str] = []
    expected_decoding = asdict(config.decoding)
    expected_contract_hash = hashlib.sha256(
        json.dumps(
            {
                "prompt_mode": config.prompt_mode,
                "thinking": False,
                "decoding": expected_decoding,
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()
    for index, row in enumerate(materialized, start=1):
        identity = str(row.get("request_id", row.get("stimulus_id", index)))
        observed_model = str(row.get("model_label", row.get("model", "")))
        if row.get("schema_version") != GENERATION_SCHEMA_VERSION:
            errors.append(f"{identity}:generation_schema")
        if row.get("protocol_version") != PROTOCOL_VERSION:
            errors.append(f"{identity}:protocol_version")
        if row.get("prompt_mode") != config.prompt_mode:
            errors.append(f"{identity}:prompt_mode")
        if row.get("native_thinking") is not False:
            errors.append(f"{identity}:native_thinking")
        if row.get("chat_template_thinking_enabled") is not False:
            errors.append(f"{identity}:chat_template_thinking_enabled")
        if row.get("decoding") != expected_decoding:
            errors.append(f"{identity}:decoding")
        if row.get("generation_contract_sha256") != expected_contract_hash:
            errors.append(f"{identity}:generation_contract_sha256")
        if config_sha256 is not None and row.get("v6_config_sha256") != config_sha256:
            errors.append(f"{identity}:v6_config_sha256")
        if model_label is not None and observed_model != model_label:
            errors.append(f"{identity}:model_label")
        if observed_model not in config.model_labels:
            errors.append(f"{identity}:unregistered_model")
            continue
        model_spec = resolve_model_spec(observed_model)
        expected_model_fields = {
            "model_id": model_spec.model_id,
            "model_revision": model_spec.revision,
            "model_family": model_spec.family,
            "model_loader_class": model_spec.loader_class,
            "chat_template_control": model_spec.chat_template_control,
        }
        for name, expected in expected_model_fields.items():
            if row.get(name) != expected:
                errors.append(f"{identity}:{name}")
        for text_name, hash_name in (
            ("user_text", "user_text_sha256"),
            ("rendered_prompt", "rendered_prompt_sha256"),
        ):
            text_value = row.get(text_name)
            if not isinstance(text_value, str) or row.get(hash_name) != hashlib.sha256(
                text_value.encode("utf-8")
            ).hexdigest():
                errors.append(f"{identity}:{hash_name}")
        source_hash = row.get("source_stimulus_sha256")
        if not isinstance(source_hash, str) or len(source_hash) != 64:
            errors.append(f"{identity}:source_stimulus_sha256")
    if errors:
        preview = errors[:20]
        suffix = "" if len(errors) <= 20 else f" (+{len(errors) - 20} more)"
        raise ValueError(f"Invalid V6 generation provenance: {preview}{suffix}")
    return {
        "schema_version": "realistic_niah_v6_generation_contract_audit_v1",
        "status": "PASS",
        "rows": len(materialized),
        "prompt_mode": config.prompt_mode,
        "model_label": model_label,
        "config_sha256": config_sha256,
        "generation_contract_sha256": expected_contract_hash,
    }


def _gold_count(row: Mapping[str, Any]) -> int:
    return int(
        row.get(
            "gold_count",
            len(row.get("gold_records", row.get("gold_pairs", ()))),
        )
    )


def registered_records(
    rows: Iterable[Mapping[str, Any]],
    config: V6Config,
    *,
    model_label: str | None = None,
    formal_only: bool = False,
) -> list[dict[str, Any]]:
    config.validate()
    selected: list[dict[str, Any]] = []
    for row in rows:
        seed = int(row.get("seed", -1))
        count = _gold_count(row)
        if str(row.get("design_variant", "v4.4")) != config.design_variant:
            continue
        if seed not in set(config.all_seeds) or count not in set(config.counts):
            continue
        observed_model = row.get("model_label", row.get("model"))
        if model_label is not None and observed_model not in {None, model_label}:
            continue
        observed_mode = row.get("prompt_mode")
        if observed_mode is not None and str(observed_mode) != config.prompt_mode:
            continue
        parsed = parse_trace_record(row) if observed_mode is not None else None
        if formal_only and parsed is not None:
            if not bool(parsed["strict_causal_eligible"]):
                continue
        value = dict(row)
        if parsed is not None:
            # Never trust a stale cached parser payload when cohort membership
            # controls a causal analysis; refresh it under the current V6 code.
            value["trace_parse"] = parsed
        value["split"] = (
            "discovery" if seed in set(config.discovery_seeds) else "confirmation"
        )
        selected.append(value)
    return selected


def audit_stimulus_panel(
    rows: Iterable[Mapping[str, Any]], config: V6Config
) -> dict[str, Any]:
    config.validate()
    selected = registered_records(rows, config)
    keys = [(int(row["seed"]), _gold_count(row)) for row in selected]
    expected = [
        (seed, count) for seed in config.all_seeds for count in config.counts
    ]
    duplicate_keys = sorted(key for key, value in Counter(keys).items() if value != 1)
    missing = sorted(set(expected) - set(keys))
    extra = sorted(set(keys) - set(expected))
    passage_hash_errors = []
    span_errors = []
    for row in selected:
        passage = str(row.get("passage", ""))
        expected_hash = row.get("passage_sha256")
        if expected_hash and hashlib.sha256(passage.encode("utf-8")).hexdigest() != expected_hash:
            passage_hash_errors.append(str(row.get("stimulus_id")))
        spans = list(row.get("active_needle_spans", ()))
        gold = list(row.get("gold_pairs", ()))
        if len(spans) != _gold_count(row) or len(gold) != _gold_count(row):
            span_errors.append(str(row.get("stimulus_id")))
    passed = not (
        duplicate_keys or missing or extra or passage_hash_errors or span_errors
    ) and len(selected) == 300
    return {
        "schema_version": "realistic_niah_v6_stimulus_audit_v1",
        "status": "PASS" if passed else "FAIL",
        "prompt_mode": config.prompt_mode,
        "selected_rows": len(selected),
        "expected_rows": 300,
        "discovery_rows": sum(int(row["seed"]) in config.discovery_seeds for row in selected),
        "confirmation_rows": sum(int(row["seed"]) in config.confirmation_seeds for row in selected),
        "duplicate_or_nonunique_cells": [list(value) for value in duplicate_keys],
        "missing_cells": [list(value) for value in missing],
        "extra_cells": [list(value) for value in extra],
        "passage_hash_errors": passage_hash_errors,
        "span_count_errors": span_errors,
    }


def parse_records(
    rows: Iterable[Mapping[str, Any]], *, include_input: bool = True
) -> list[dict[str, Any]]:
    output = []
    for row in rows:
        parsed = parse_trace_record(row)
        output.append(({**dict(row), "trace_parse": parsed}) if include_input else parsed)
    return output


def audit_generation_panel(
    rows: Iterable[Mapping[str, Any]],
    config: V6Config,
    *,
    model_label: str,
    require_complete: bool = True,
    seed_role: str = "all",
    config_sha256: str | None = None,
) -> dict[str, Any]:
    config.validate()
    if seed_role not in {"all", "discovery", "confirmation"}:
        raise ValueError(f"Unknown V6 seed role: {seed_role}")
    materialized = list(rows)
    contract_audit = validate_generation_contracts(
        materialized,
        config,
        model_label=model_label,
        config_sha256=config_sha256,
    )
    selected = registered_records(materialized, config, model_label=model_label)
    if seed_role != "all":
        selected = [row for row in selected if row["split"] == seed_role]
    parsed = [parse_trace_record(row) for row in selected]
    keys = [(int(row["seed"]), _gold_count(row)) for row in selected]
    duplicate_keys = sorted(key for key, value in Counter(keys).items() if value != 1)
    seeds = (
        config.all_seeds
        if seed_role == "all"
        else (
            config.discovery_seeds
            if seed_role == "discovery"
            else config.confirmation_seeds
        )
    )
    expected = {(seed, count) for seed in seeds for count in config.counts}
    strict = [bool(value["strict_causal_eligible"]) for value in parsed]
    format_ok = [bool(value["enumeration_format_compliant"]) for value in parsed]
    exact = [bool(value["exact_count"]) for value in parsed]
    complete_ok = set(keys) == expected and len(selected) == len(expected)
    passed = not duplicate_keys and (complete_ok if require_complete else bool(selected))
    return {
        "schema_version": "realistic_niah_v6_generation_audit_v1",
        "status": "PASS" if passed else "FAIL",
        "prompt_mode": config.prompt_mode,
        "model_label": model_label,
        "seed_role": seed_role,
        "rows": len(selected),
        "expected_rows": len(expected),
        "complete_panel": complete_ok,
        "duplicate_or_nonunique_cells": [list(value) for value in duplicate_keys],
        "missing_cells": [list(value) for value in sorted(expected - set(keys))],
        "strict_causal_eligible_rows": sum(strict),
        "strict_causal_eligible_fraction": sum(strict) / len(strict) if strict else 0.0,
        "format_compliant_rows": sum(format_ok),
        "format_compliant_fraction": sum(format_ok) / len(format_ok) if format_ok else 0.0,
        "exact_count_rows": sum(exact),
        "exact_count_fraction": sum(exact) / len(exact) if exact else 0.0,
        "generation_contract_audit": contract_audit,
        "strict_discovery_rows": sum(
            keep and int(row["seed"]) in config.discovery_seeds
            for keep, row in zip(strict, selected)
        ),
        "strict_confirmation_rows": sum(
            keep and int(row["seed"]) in config.confirmation_seeds
            for keep, row in zip(strict, selected)
        ),
    }
